version: "3"
services:
### Postgres Database ###

  stc-postgres:
    image: "postgres"
    container_name: stc-postgres
    networks:
      - stc-network
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: BDBRIEF13

 #Back-end Spring Boot Application
  app:
    image: "omardbaa/stc-app"
    container_name: stc-app
    environment:
      - DB_SERVER=devops-postgres
      - POSTGRES_DB=BDBRIEF13
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456 
    networks:
      - stc-network
    ports:
      - "8081:8080"
    links:
      - stc-postgres

      
networks: 
    stc-network:
     
